# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lssm',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/lssm',
                'lib_path': 'lssm'},
  'syms': {'lssm.loading': {'lssm.loading.load_ossl': ('loading.html#load_ossl', 'lssm/loading.py')}, 'lssm.preprocessing': {}}}
