# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_hooks.ipynb.

# %% auto 0
__all__ = ['Hook']

# %% ../nbs/08_hooks.ipynb 3
# from copy import copy
# import math
# import fastcore.all as fc
# from fastprogress import progress_bar, master_bar
# from operator import attrgetter
# from collections.abc import Mapping

# import matplotlib.pyplot as plt

# import torch
# from torchvision import transforms as T
# from torcheval.metrics import Mean

# %% ../nbs/08_hooks.ipynb 13
class Hook():
    def __init__(self, m, f): self.hook = m.register_forward_hook(partial(f, self))
    def remove(self): self.hook.remove()
    def __del__(self): self.remove()
